<html>
  <head>
    <meta charset="UTF-8">
  </head>
  <body>
    <p>Hello <?php echo $firstName; ?>,</p>

    <p><?php echo $adminNames; ?> has assigned you to the <strong><?php echo $projectName; ?></strong> project.</p>

    <p>Sign in at your WorkLog account to log time and generate timesheets and reports.</p>

    <hr />
    <p>
      <small>Send by Worklog API on <?php echo $dateTimeNow; ?></small>
    </p>


  </body>
</html>
