Hello <?php echo $firstName; ?>,

<?php echo $adminNames; ?> has just removed you from "<?php echo $projectName; ?>" project. 

Time your've logged is still there and you can access your timesheets and reports at any time. 
It wouldn't be possible to log more work into this project. 

You are still full-featured WorkLog member and can log time to other projects or even create 
your own project and build a team.


---
Send by Worklog API on <?php echo $dateTimeNow; ?>
