<html>
  <head>
    <meta charset="UTF-8">
  </head>
  <body>
    <p>Hello <?php echo $firstName; ?>,</p>

    <p><?php echo $adminNames; ?> has just removed you from <strong><?php echo $projectName; ?></strong> project.</p>

    <p>
      Time your've logged is still there and you can access your timesheets and reports at any time.
      It wouldn't be possible to log more work into this project.
    </p>

    <p>
      You are still full-featured WorkLog member and can log time to other projects or even create
      your own project and build a team.
    </p>

    <hr />
    <p>
      <small>Send by Worklog API on <?php echo $dateTimeNow; ?></small>
    </p>

  </body>
</html>
